server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
      ddl-auto: create
      show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/kids_queue?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!

  security:
    user:
      name: test
      password: 1234


