name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    services:
      mysql:
        image: mysql:8.0.36
        env:
          MYSQL_ROOT_PASSWORD: root1234!!
          MYSQL_DATABASE: kids_queue
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u yourusername --password=yourpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5  

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      # GitHub secrets에서 jwt 키 값 가져와서 셋팅
      - name: Set application.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          jwt.secret: ${{secrets.JWT_KEY}}


      # GitHub secrets에서 DB 설정 값 가져와서 셋팅
      # Todo 추후 수정 예정 (배포에서 안 쓴다면 삭제)
      - name: Set application-prod.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application-prod.yml
        env:
          spring.datasource.url: ${{secrets.DB_URL}}
          spring.datasource.username: ${{secrets.DB_USERNAME}}
          spring.datasource.password: ${{secrets.DB_PASSWORD}}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      # Permission denied 해결을 위해 쓰기 권한 부여
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      # Spring Boot Build & test
      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test

      - name: Test with Gradle
        run: ./gradlew test


  dependency-submission:

    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
